imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_addresses: ['me@example.com']
hautelook_alice:
    fixtures_path: 'Resources/fixtures/orm'

# config.yml
knp_snappy:
    pdf:
        enabled:    true
        binary:    "/usr/bin/wkhtmltopdf"
#connexion windows
#         binary:    "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
#connexion linux
#         binary:  /usr/local/bin/wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     "/usr/bin/wkhtmltoimage"
#connexion windows
#         binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\""
#connexion linux
#         binary:  /usr/local/bin/wkhtmltoimage
        options:    []
    temporary_folder: %kernel.cache_dir%/snappy

#            binary:     /usr/local/bin/wkhtmltopdf #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"" for Windows users
#        binary:     /usr/local/bin/wkhtmltoimage #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" for Windows users
