<?php

namespace TytdBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function derniersArticles($limite = null) {
        {
            $qb = $this->createQueryBuilder('a')
                ->select('a, c')
                ->leftJoin('a.commentaire', 'c')
                ->addOrderBy('a.date', 'DESC');

            if (false === is_null($limite))
                $qb->setMaxResults($limite);

            return $qb->getQuery()
                ->getResult();
        }
    }

}


