<?php

namespace TytdBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    function findWithLimit($nomCa = 'voyage') {
        return $this->createQueryBuilder('c')
            ->where('c.nomCa = :nomCa')
            ->setParameter('nomCa', $nomCa)
            ->getQuery()
            ->execute();
    }
}
