<?php

namespace TytdBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    function findWithLimit($nomCa = 'voyage')
    {
        return $this->createQueryBuilder('c')
            ->where('c.nomCa = :nomCa')
            ->setParameter('nomCa', $nomCa)
            ->getQuery()
            ->execute();
    }

    function findOneCateg($idCat)
    {
        return $this->createQueryBuilder('c')
            ->select('c, e')

            ->leftJoin('c.evenement', 'e')
            ->setParameter('id', $idCat)
            ->addOrderBy("c.evenement.dateE", 'DESC')
            ->getQuery()
            ->execute();
    }


}
