<?php

namespace TytdBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    function findWithLimit($nomCa = 'voyage')
    {
        return $this->createQueryBuilder('c')
            ->where('c.nomCa = :nomCa')
            ->setParameter('nomCa', $nomCa)
            ->getQuery()
            ->execute();
    }


    function randomIndex($limite)
    {
        $count = $this->createQueryBuilder('cat')
            ->select('COUNT(cat)')
            ->getQuery()
            ->getSingleScalarResult();

        $this->createQueryBuilder('cat')
            ->where('cat.nomCa = :nomCa')
            ->setFirstResult(rand(0, $count - 1))
            ->setMaxResults($limite);

        return $count->getQuery();

        }


}
