<?php

namespace TytdBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function derniersCommentaires($limite = null) {
        {
            $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->addOrderBy('c.dateC', 'DESC');

            if (false === is_null($limite))
                $qb->setMaxResults($limite);

            return $qb->getQuery()
                ->getResult();
        }
    }

}
