<?php

namespace TytdBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function derniersContacts($limite = null) {
        {
            $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->addOrderBy('c.date', 'DESC');

            if (false === is_null($limite))
                $qb->setMaxResults($limite);

            return $qb->getQuery()
                ->getResult();
        }
    }
}
